/* ============================================================
   DATA.JS — Hotel Dataset, 52 Entitas, KOTA Yogyakarta Only
   WebGIS SIG Terapan — Geomatika UPN "Veteran" Yogyakarta

   FOTO HOTEL — Cara input foto real (3 opsi):
   1. URL website hotel langsung:
      photo: "https://namahotel.com/images/front.jpg"
   2. Google Places Photo (butuh API Key GCP):
      photo: "https://maps.googleapis.com/maps/api/place/photo?maxwidth=420&photoreference=PHOTO_REF&key=API_KEY"
   3. Simpan foto ke folder /img/ lalu:
      photo: "img/nama-hotel.jpg"

   Hotel di luar Kota Yogyakarta yang telah DIHAPUS:
   × Hyatt Regency (Ngaglik/Sleman)
   × Royal Ambarrukmo (Depok/Sleman)
   × Grand Mercure Adi Sucipto (Depok/Sleman)
   × Sheraton Mustika Resort (Sleman)
   × Rich Jogja Hotel (Mlati/Sleman)
   × Alana Hotel (Ngaglik/Sleman)
   × Premiere Park Hotel (Banguntapan/Bantul)
   ============================================================ */

const YOGYA_CENTER = [-7.7956, 110.3695];
const YOGYA_ZOOM = 13;

const CAT_META = {
  "Bintang 5": { color: "#D97706", bg: "rgba(217,119,6,.12)", label: "★★★★★" },
  "Bintang 4": { color: "#2563EB", bg: "rgba(37,99,235,.10)", label: "★★★★" },
  "Bintang 3": { color: "#7C3AED", bg: "rgba(124,58,237,.10)", label: "★★★" },
  "Bintang 2": { color: "#64748B", bg: "rgba(100,116,139,.12)", label: "★★" },
  Butik: { color: "#0B9F97", bg: "rgba(11,159,151,.10)", label: "BOUTIQUE" },
};

const PHOTOS = {
  b5: [
    "https://images.unsplash.com/photo-1551882547-ff40c4a49f8e?w=420&q=80",
    "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=420&q=80",
    "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=420&q=80",
    "https://images.unsplash.com/photo-1455587734955-081b22074882?w=420&q=80",
    "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=420&q=80",
  ],
  b4: [
    "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=420&q=80",
    "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=420&q=80",
    "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=420&q=80",
    "https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=420&q=80",
    "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=420&q=80",
  ],
  b3: [
    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=420&q=80",
    "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=420&q=80",
    "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=420&q=80",
    "https://images.unsplash.com/photo-1551776235-dde6d482980b?w=420&q=80",
    "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=420&q=80",
  ],
  b2: [
    "https://images.unsplash.com/photo-1586611292717-f828b167408c?w=420&q=80",
    "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=420&q=80",
    "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=420&q=80",
  ],
  butik: [
    "https://images.unsplash.com/photo-1587985064135-0366536eab42?w=420&q=80",
    "https://images.unsplash.com/photo-1605346434674-a440ca4dc4c0?w=420&q=80",
  ],
};

/* ============================================================
   WSM — Weighted Sum Model (Modul Acara 5 SIG Terapan UPN)

   Rumus: WSM = Σ (bobot_i × nilai_ternormalisasi_i)

   Kriteria         │ Bobot │ Normalisasi
   ─────────────────┼───────┼──────────────────────────────
   Heritage Prox.   │ 0.30  │ skor dari klasifikasi landuse
   Connectivity     │ 0.25  │ nilai / 100
   Service Efisiensi│ 0.25  │ (100 - serviceLoad) / 100
   Geodesign Score  │ 0.20  │ nilai / 10
   ─────────────────┴───────┴──────────────────────────────
   Skor akhir dikali 10 → skala 0–10
   ============================================================ */
const WSM_WEIGHTS = {
  heritage: 0.3,
  connectivity: 0.25,
  efficiency: 0.25,
  geodesign: 0.2,
};

const HERITAGE_SCORE = {
  "Kawasan Heritage": 1.0,
  "Zonasi Cagar Budaya": 1.0,
  "Kawasan Kraton": 0.9,
  "Kawasan Bersejarah": 0.8,
  "Kawasan Pariwisata": 0.7,
  "Komersial/Jasa": 0.4,
  "Kawasan Campuran": 0.3,
  "Ruang Terbuka Hijau": 0.3,
  Permukiman: 0.2,
};

function calcWSM(h) {
  const h_norm = Math.max(...h.landuse.map((l) => HERITAGE_SCORE[l] || 0.2));
  const c_norm = h.connectivity / 100;
  const e_norm = (100 - h.serviceLoad) / 100;
  const g_norm = h.geodesign / 10;
  const raw =
    WSM_WEIGHTS.heritage * h_norm +
    WSM_WEIGHTS.connectivity * c_norm +
    WSM_WEIGHTS.efficiency * e_norm +
    WSM_WEIGHTS.geodesign * g_norm;
  return +(raw * 10).toFixed(1);
}

/* ============================================================
   DATASET — 52 Hotel, Kota Yogyakarta (14 Kecamatan)
   ============================================================ */
const HOTELS_RAW = [
  /* ═══ BINTANG 5 ════════════════════════════════════════ */
  {
    id: "YK-HTL-401",
    name: "Grand Inna Malioboro",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7928,
    lng: 110.365,
    address: "Jl. Malioboro No.60, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 241,
    capacity: 88,
    phone: "(0274) 563041",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.1 km",
    dist_kraton: "1.2 km",
    photo: PHOTOS.b5[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 8.1,
    connectivity: 94,
    serviceLoad: 71,
    notes:
      "Berada di jantung koridor heritage Malioboro. Bangunan bersejarah dilindungi SK Gubernur DIY.",
  },
  {
    id: "YK-HTL-402",
    name: "The Phoenix Hotel Yogyakarta",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7902,
    lng: 110.3642,
    address: "Jl. Jend. Sudirman No.9, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 143,
    capacity: 92,
    phone: "(0274) 566617",
    distance_tugu: "0.4 km dari Tugu",
    dist_malio: "0.3 km",
    dist_kraton: "1.4 km",
    photo: PHOTOS.b5[1],
    landuse: ["Zonasi Cagar Budaya", "Komersial/Jasa"],
    geodesign: 8.4,
    connectivity: 92,
    serviceLoad: 64,
    notes:
      "Dalam koridor heritage Kawasan Cagar Budaya Jetis. Regulasi tinggi bangunan max 18m.",
  },
  {
    id: "YK-HTL-403",
    name: "Tentrem Hotel Yogyakarta",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7885,
    lng: 110.3665,
    address: "Jl. P. Diponegoro No.72, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 197,
    capacity: 85,
    phone: "(0274) 563888",
    distance_tugu: "0.6 km dari Tugu",
    dist_malio: "0.5 km",
    dist_kraton: "1.5 km",
    photo: PHOTOS.b5[2],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 8.7,
    connectivity: 96,
    serviceLoad: 58,
    notes:
      "Hotel bintang 5 konsep budaya Jawa kontemporer. Aksesibilitas pejalan kaki sangat baik.",
  },
  {
    id: "YK-HTL-404",
    name: "Melia Purosani Hotel",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7892,
    lng: 110.371,
    address: "Jl. Suryotomo No.31, Ngupasan",
    kecamatan: "Gondomanan",
    rooms: 326,
    capacity: 79,
    phone: "(0274) 589521",
    distance_tugu: "0.8 km dari Tugu",
    dist_malio: "0.6 km",
    dist_kraton: "0.9 km",
    photo: PHOTOS.b5[3],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 8.2,
    connectivity: 89,
    serviceLoad: 73,
    notes:
      "Hotel MICE terbesar di pusat kota. Kapasitas konvensi mendukung kegiatan skala internasional.",
  },
  {
    id: "YK-HTL-409",
    name: "Tugu Yogyakarta Hotel",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7847,
    lng: 110.3636,
    address: "Jl. P. Mangkubumi No.18, Gowongan",
    kecamatan: "Jetis",
    rooms: 48,
    capacity: 70,
    phone: "(0274) 563611",
    distance_tugu: "0.1 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.7 km",
    photo: PHOTOS.b5[4],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 8.9,
    connectivity: 97,
    serviceLoad: 48,
    notes:
      "Butik hotel bintang 5 ikonik di samping Tugu Yogyakarta. Koleksi artefak seni Jawa klasik.",
  },

  /* ═══ BINTANG 4 ════════════════════════════════════════ */
  {
    id: "YK-HTL-410",
    name: "Harper Malioboro by ASTON",
    category: "Bintang 4",
    stars: 4,
    lat: -7.796,
    lng: 110.3638,
    address: "Jl. Dagen No.47, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 166,
    capacity: 91,
    phone: "(0274) 566066",
    distance_tugu: "0.2 km dari Tugu",
    dist_malio: "0.1 km",
    dist_kraton: "1.3 km",
    photo: PHOTOS.b4[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 7.8,
    connectivity: 97,
    serviceLoad: 82,
    notes:
      "Occupancy tertinggi di kawasan Malioboro. Beban layanan melebihi optimal pada peak season.",
  },
  {
    id: "YK-HTL-411",
    name: "Hotel Santika Premiere Jogja",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7882,
    lng: 110.3734,
    address: "Jl. Jend. Sudirman No.19, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 212,
    capacity: 74,
    phone: "(0274) 563036",
    distance_tugu: "1.1 km dari Tugu",
    dist_malio: "0.9 km",
    dist_kraton: "1.1 km",
    photo: PHOTOS.b4[1],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.9,
    connectivity: 91,
    serviceLoad: 57,
    notes:
      "Lokasi strategis di segitiga emas pariwisata Yogyakarta. Akses mudah ke Malioboro dan Kraton.",
  },
  {
    id: "YK-HTL-412",
    name: "Novotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7868,
    lng: 110.3743,
    address: "Jl. Jend. Sudirman No.89, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 195,
    capacity: 69,
    phone: "(0274) 580930",
    distance_tugu: "1.3 km dari Tugu",
    dist_malio: "1.1 km",
    dist_kraton: "0.9 km",
    photo: PHOTOS.b4[2],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.6,
    connectivity: 88,
    serviceLoad: 52,
    notes:
      "Desain mempertimbangkan koridor pandang visual ke Merapi. Sesuai RTBL Koridor Sudirman.",
  },
  {
    id: "YK-HTL-413",
    name: "Indoluxe Hotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7843,
    lng: 110.3688,
    address: "Jl. Kapten Piere Tendean, Wirobrajan",
    kecamatan: "Wirobrajan",
    rooms: 178,
    capacity: 77,
    phone: "(0274) 566222",
    distance_tugu: "1.8 km dari Tugu",
    dist_malio: "1.6 km",
    dist_kraton: "1.9 km",
    photo: PHOTOS.b4[3],
    landuse: ["Komersial/Jasa", "Permukiman"],
    geodesign: 7.4,
    connectivity: 82,
    serviceLoad: 59,
    notes:
      "Kawasan transisi komersial-permukiman. Dampak terhadap jaringan jalan perlu monitoring.",
  },
  {
    id: "YK-HTL-414",
    name: "Cavinton Hotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.795,
    lng: 110.382,
    address: "Jl. Ipda Tut Harsono No.47, Semaki",
    kecamatan: "Umbulharjo",
    rooms: 134,
    capacity: 83,
    phone: "(0274) 547777",
    distance_tugu: "2.9 km dari Tugu",
    dist_malio: "2.7 km",
    dist_kraton: "2.3 km",
    photo: PHOTOS.b4[4],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.1,
    connectivity: 79,
    serviceLoad: 66,
    notes:
      "Kawasan timur kota aksesibilitas berkembang pesat. Infrastruktur jalan dalam kondisi baik.",
  },
  {
    id: "YK-HTL-415",
    name: "Swiss-Belinn Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.8105,
    lng: 110.3635,
    address: "Jl. Parangtritis Km 1, Mantrijeron",
    kecamatan: "Mantrijeron",
    rooms: 156,
    capacity: 72,
    phone: "(0274) 411234",
    distance_tugu: "3.4 km dari Tugu",
    dist_malio: "3.1 km",
    dist_kraton: "2.6 km",
    photo: PHOTOS.b4[0],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.3,
    connectivity: 76,
    serviceLoad: 54,
    notes:
      "Koridor selatan menuju Parangtritis. Potensi wisata alam tinggi, aksesibilitas berkembang.",
  },
  {
    id: "YK-HTL-416",
    name: "Harris Hotel & Conventions Malioboro",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7942,
    lng: 110.3644,
    address: "Jl. Pabringan No.2, Ngupasan",
    kecamatan: "Gondomanan",
    rooms: 222,
    capacity: 80,
    phone: "(0274) 588222",
    distance_tugu: "0.5 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "0.7 km",
    photo: PHOTOS.b4[1],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 7.7,
    connectivity: 95,
    serviceLoad: 78,
    notes:
      "Hotel convention skala besar di pusat kota. Ballroom kapasitas 2000 pax mendukung MICE.",
  },
  {
    id: "YK-HTL-418",
    name: "Grand Quality Hotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7815,
    lng: 110.3845,
    address: "Jl. Laksda Adisucipto No.48, Demangan",
    kecamatan: "Gondokusuman",
    rooms: 176,
    capacity: 68,
    phone: "(0274) 485858",
    distance_tugu: "2.4 km dari Tugu",
    dist_malio: "2.6 km",
    dist_kraton: "2.8 km",
    photo: PHOTOS.b4[2],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.2,
    connectivity: 83,
    serviceLoad: 55,
    notes:
      "Hotel bisnis di koridor timur kota. Aksesibilitas kendaraan bermotor sangat baik.",
  },
  {
    id: "YK-HTL-420",
    name: "The Jayakarta Yogyakarta Hotel",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7862,
    lng: 110.3852,
    address: "Jl. Laksda Adisucipto No.28, Demangan",
    kecamatan: "Gondokusuman",
    rooms: 189,
    capacity: 67,
    phone: "(0274) 564222",
    distance_tugu: "2.6 km dari Tugu",
    dist_malio: "2.8 km",
    dist_kraton: "3.0 km",
    photo: PHOTOS.b4[3],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.0,
    connectivity: 81,
    serviceLoad: 53,
    notes:
      "Kolam renang outdoor dengan view taman. Fasilitas spa dan fitness center lengkap.",
  },
  {
    id: "YK-HTL-443",
    name: "Grand Tjokro Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.8015,
    lng: 110.3895,
    address: "Jl. Gowongan Kidul No.50, Semaki",
    kecamatan: "Umbulharjo",
    rooms: 162,
    capacity: 71,
    phone: "(0274) 543555",
    distance_tugu: "3.0 km dari Tugu",
    dist_malio: "2.8 km",
    dist_kraton: "2.4 km",
    photo: PHOTOS.b4[4],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.0,
    connectivity: 78,
    serviceLoad: 60,
    notes:
      "Hotel bisnis modern Umbulharjo. Fasilitas ballroom dan ruang meeting lengkap.",
  },

  {
    id: "YK-HTL-445",
    name: "Grand Palace Hotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7976,
    lng: 110.373,
    address: "Jl. Mangkuyudan No.1, Mantrijeron",
    kecamatan: "Mantrijeron",
    rooms: 138,
    capacity: 73,
    phone: "(0274) 371000",
    distance_tugu: "2.2 km dari Tugu",
    dist_malio: "2.0 km",
    dist_kraton: "1.2 km",
    photo: PHOTOS.b4[1],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.4,
    connectivity: 84,
    serviceLoad: 62,
    notes:
      "Dekat kawasan Kraton dan Taman Sari. Konsep heritage dengan fasilitas modern.",
  },

  /* ═══ BINTANG 3 ════════════════════════════════════════ */
  {
    id: "YK-HTL-422",
    name: "Artotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.798,
    lng: 110.3742,
    address: "Jl. Kaliurang No.14, Baciro",
    kecamatan: "Gondokusuman",
    rooms: 109,
    capacity: 86,
    phone: "(0274) 547200",
    distance_tugu: "1.9 km dari Tugu",
    dist_malio: "1.7 km",
    dist_kraton: "2.1 km",
    photo: PHOTOS.b3[0],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.0,
    connectivity: 84,
    serviceLoad: 71,
    notes:
      "Hotel seni kontemporer. Koleksi artwork lokal menjadi nilai jual unik bagi wisatawan budaya.",
  },
  {
    id: "YK-HTL-423",
    name: "Ibis Styles Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7927,
    lng: 110.3707,
    address: "Jl. Dagen No.67, Ngampilan",
    kecamatan: "Gedongtengen",
    rooms: 130,
    capacity: 93,
    phone: "(0274) 580555",
    distance_tugu: "0.5 km dari Tugu",
    dist_malio: "0.3 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b3[1],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 7.5,
    connectivity: 95,
    serviceLoad: 88,
    notes:
      "Occupancy sangat tinggi (93%). Terindikasi beban layanan berlebih pada musim peak.",
  },
  {
    id: "YK-HTL-424",
    name: "Neo Malioboro Hotel",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7919,
    lng: 110.3648,
    address: "Jl. Pajeksan No.18, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 98,
    capacity: 78,
    phone: "(0274) 589300",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.1 km",
    photo: PHOTOS.b3[2],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.8,
    connectivity: 96,
    serviceLoad: 75,
    notes:
      "Lokasi premium kawasan heritage. Indeks kerapatan bangunan tinggi, limitasi ekspansi vertikal.",
  },
  {
    id: "YK-HTL-425",
    name: "Hotel Mutiara Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7943,
    lng: 110.3669,
    address: "Jl. Malioboro No.18, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 93,
    capacity: 65,
    phone: "(0274) 563814",
    distance_tugu: "0.4 km dari Tugu",
    dist_malio: "0.1 km",
    dist_kraton: "1.2 km",
    photo: PHOTOS.b3[3],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.5,
    connectivity: 93,
    serviceLoad: 62,
    notes:
      "Hotel heritage generasi pertama di Malioboro. Nilai arsitektural dilindungi sebagai cagar budaya.",
  },
  {
    id: "YK-HTL-426",
    name: "Hotel Pesona Jogja",
    category: "Bintang 3",
    stars: 3,
    lat: -7.805,
    lng: 110.372,
    address: "Jl. Prawirotaman No.1, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 87,
    capacity: 70,
    phone: "(0274) 373900",
    distance_tugu: "2.5 km dari Tugu",
    dist_malio: "2.3 km",
    dist_kraton: "1.8 km",
    photo: PHOTOS.b3[4],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 6.9,
    connectivity: 77,
    serviceLoad: 58,
    notes:
      "Kawasan Prawirotaman pusat hotel butik. Karakteristik kampung wisata kepadatan rendah.",
  },
  {
    id: "YK-HTL-427",
    name: "Puri Artha Hotel",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7998,
    lng: 110.3878,
    address: "Jl. Cendrawasih No.36, Semaki",
    kecamatan: "Umbulharjo",
    rooms: 76,
    capacity: 60,
    phone: "(0274) 563288",
    distance_tugu: "3.1 km dari Tugu",
    dist_malio: "2.9 km",
    dist_kraton: "2.5 km",
    photo: PHOTOS.b3[0],
    landuse: ["Permukiman", "Komersial/Jasa"],
    geodesign: 6.3,
    connectivity: 74,
    serviceLoad: 48,
    notes:
      "Hotel di kawasan permukiman dengan konversi lahan bertahap. Dampak terhadap RTH perlu evaluasi.",
  },
  {
    id: "YK-HTL-428",
    name: "Saphir Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7915,
    lng: 110.3762,
    address: "Jl. Laksda Adisucipto No.38, Demangan",
    kecamatan: "Gondokusuman",
    rooms: 118,
    capacity: 73,
    phone: "(0274) 485555",
    distance_tugu: "2.2 km dari Tugu",
    dist_malio: "2.0 km",
    dist_kraton: "2.4 km",
    photo: PHOTOS.b3[1],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.2,
    connectivity: 86,
    serviceLoad: 61,
    notes:
      "Koridor timur menuju bandara. Segmen tamu didominasi wisatawan transit.",
  },
  {
    id: "YK-HTL-429",
    name: "Whiz Prime Hotel Malioboro",
    category: "Bintang 3",
    stars: 3,
    lat: -7.79,
    lng: 110.3663,
    address: "Jl. Mangkubumi No.52, Gowongan",
    kecamatan: "Jetis",
    rooms: 122,
    capacity: 81,
    phone: "(0274) 566300",
    distance_tugu: "0.7 km dari Tugu",
    dist_malio: "0.5 km",
    dist_kraton: "1.3 km",
    photo: PHOTOS.b3[2],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.0,
    connectivity: 90,
    serviceLoad: 74,
    notes:
      "Dekat kawasan Malioboro dan Stasiun Tugu. Aksesibilitas transit sangat baik.",
  },
  {
    id: "YK-HTL-430",
    name: "Dafam Fortuna Malioboro",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7878,
    lng: 110.365,
    address: "Jl. Mangkubumi No.47, Gowongan",
    kecamatan: "Jetis",
    rooms: 105,
    capacity: 77,
    phone: "(0274) 587200",
    distance_tugu: "0.9 km dari Tugu",
    dist_malio: "0.7 km",
    dist_kraton: "1.5 km",
    photo: PHOTOS.b3[3],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 6.9,
    connectivity: 88,
    serviceLoad: 70,
    notes:
      "Hotel budget premium di koridor Mangkubumi. Target pasar backpacker kelas menengah.",
  },
  {
    id: "YK-HTL-431",
    name: "Horison Express Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7948,
    lng: 110.3672,
    address: "Jl. Dagen No.85, Ngampilan",
    kecamatan: "Gedongtengen",
    rooms: 114,
    capacity: 84,
    phone: "(0274) 563999",
    distance_tugu: "0.4 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.1 km",
    photo: PHOTOS.b3[4],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.7,
    connectivity: 94,
    serviceLoad: 79,
    notes:
      "Hotel express dengan lokasi prime. Fasilitas efisien untuk wisatawan singkat.",
  },
  {
    id: "YK-HTL-432",
    name: "Adhisthana Hotel Prawirotaman",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8065,
    lng: 110.3695,
    address: "Jl. Prawirotaman II No.16, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 81,
    capacity: 68,
    phone: "(0274) 377222",
    distance_tugu: "2.7 km dari Tugu",
    dist_malio: "2.5 km",
    dist_kraton: "2.0 km",
    photo: PHOTOS.b3[0],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 6.8,
    connectivity: 75,
    serviceLoad: 56,
    notes:
      "Butik hotel tenang di kawasan Prawirotaman. Kolam renang privat dan restoran rooftop.",
  },
  {
    id: "YK-HTL-433",
    name: "Tjokro Style Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7858,
    lng: 110.3756,
    address: "Jl. Jend. Sudirman No.75, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 96,
    capacity: 72,
    phone: "(0274) 512345",
    distance_tugu: "1.4 km dari Tugu",
    dist_malio: "1.2 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b3[1],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 6.9,
    connectivity: 85,
    serviceLoad: 63,
    notes:
      "Hotel boutique dengan sentuhan desain Jawa modern. Meeting room kapasitas 200 pax.",
  },
  {
    id: "YK-HTL-434",
    name: "Brongto Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.798,
    lng: 110.3844,
    address: "Jl. Aipda Tut Harsono No.15, Muja Muju",
    kecamatan: "Umbulharjo",
    rooms: 88,
    capacity: 66,
    phone: "(0274) 542200",
    distance_tugu: "2.8 km dari Tugu",
    dist_malio: "2.6 km",
    dist_kraton: "2.2 km",
    photo: PHOTOS.b3[2],
    landuse: ["Komersial/Jasa", "Permukiman"],
    geodesign: 6.4,
    connectivity: 73,
    serviceLoad: 51,
    notes:
      "Hotel keluarga di kawasan tenang Umbulharjo. Parkir luas dan restoran kapasitas 150 kursi.",
  },
  {
    id: "YK-HTL-435",
    name: "Puri Pangeran Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8003,
    lng: 110.3622,
    address: "Jl. Rotowijayan No.5, Kraton",
    kecamatan: "Kraton",
    rooms: 72,
    capacity: 62,
    phone: "(0274) 372055",
    distance_tugu: "2.1 km dari Tugu",
    dist_malio: "1.5 km",
    dist_kraton: "0.3 km",
    photo: PHOTOS.b3[3],
    landuse: ["Kawasan Heritage", "Kawasan Kraton"],
    geodesign: 7.3,
    connectivity: 80,
    serviceLoad: 55,
    notes:
      "Dalam kawasan buffer Kraton Yogyakarta. Regulasi ketat pembangunan vertikal, max 8m.",
  },
  {
    id: "YK-HTL-436",
    name: "Grage Jogja Hotel",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8018,
    lng: 110.3578,
    address: "Jl. Tentara Rakyat Mataram No.10, Pakuncen",
    kecamatan: "Wirobrajan",
    rooms: 94,
    capacity: 69,
    phone: "(0274) 562646",
    distance_tugu: "2.4 km dari Tugu",
    dist_malio: "1.9 km",
    dist_kraton: "1.6 km",
    photo: PHOTOS.b3[4],
    landuse: ["Komersial/Jasa", "Permukiman"],
    geodesign: 6.5,
    connectivity: 76,
    serviceLoad: 57,
    notes:
      "Hotel konvensional dengan kolam renang. Dekat pusat perbelanjaan dan rumah makan lokal.",
  },
  {
    id: "YK-HTL-446",
    name: "Hotel Garuda Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7935,
    lng: 110.3685,
    address: "Jl. Malioboro No.72, Ngupasan",
    kecamatan: "Gondomanan",
    rooms: 103,
    capacity: 76,
    phone: "(0274) 562353",
    distance_tugu: "0.6 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "0.8 km",
    photo: PHOTOS.b3[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 7.1,
    connectivity: 93,
    serviceLoad: 72,
    notes:
      "Salah satu hotel tertua di kawasan Malioboro. Nilai historis dan posisi strategis sangat tinggi.",
  },
  {
    id: "YK-HTL-447",
    name: "Hotel Limaran Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7975,
    lng: 110.3628,
    address: "Jl. Wirobrajan No.5, Pakuncen",
    kecamatan: "Wirobrajan",
    rooms: 78,
    capacity: 63,
    phone: "(0274) 374100",
    distance_tugu: "1.8 km dari Tugu",
    dist_malio: "1.6 km",
    dist_kraton: "1.7 km",
    photo: PHOTOS.b3[1],
    landuse: ["Komersial/Jasa", "Permukiman"],
    geodesign: 6.4,
    connectivity: 75,
    serviceLoad: 55,
    notes:
      "Hotel budget bintang 3 di kawasan Wirobrajan. Sasaran tamu keluarga dan wisatawan lokal.",
  },
  {
    id: "YK-HTL-448",
    name: "Hotel Grand Dafam Rohan Jogja",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8005,
    lng: 110.3672,
    address: "Jl. Parangtritis No.99, Mantrijeron",
    kecamatan: "Mantrijeron",
    rooms: 91,
    capacity: 67,
    phone: "(0274) 382900",
    distance_tugu: "2.3 km dari Tugu",
    dist_malio: "2.0 km",
    dist_kraton: "1.4 km",
    photo: PHOTOS.b3[2],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 6.8,
    connectivity: 79,
    serviceLoad: 59,
    notes:
      "Kawasan selatan menuju wisata alam Parangtritis. Konsep desain minimalis kontemporer.",
  },
  {
    id: "YK-HTL-449",
    name: "Rumah Berbudaya Kotagede",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8122,
    lng: 110.3845,
    address: "Jl. Kemasan No.14, Purbayan",
    kecamatan: "Kotagede",
    rooms: 45,
    capacity: 55,
    phone: "(0274) 385123",
    distance_tugu: "4.0 km dari Tugu",
    dist_malio: "3.8 km",
    dist_kraton: "2.9 km",
    photo: PHOTOS.b3[3],
    landuse: ["Kawasan Heritage", "Kawasan Bersejarah"],
    geodesign: 7.6,
    connectivity: 68,
    serviceLoad: 44,
    notes:
      "Hotel heritage di kawasan Kotagede, pusat kerajinan perak warisan Mataram Islam.",
  },

  {
    id: "YK-HTL-451",
    name: "Grand Rohan Jogja Hotel",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7962,
    lng: 110.3558,
    address: "Jl. Nitikan No.15, Ngampilan",
    kecamatan: "Ngampilan",
    rooms: 84,
    capacity: 72,
    phone: "(0274) 383838",
    distance_tugu: "2.1 km dari Tugu",
    dist_malio: "1.9 km",
    dist_kraton: "2.0 km",
    photo: PHOTOS.b3[0],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 6.7,
    connectivity: 77,
    serviceLoad: 61,
    notes:
      "Hotel di kawasan Ngampilan. Jarak kaki ke Malioboro sekitar 20 menit.",
  },
  {
    id: "YK-HTL-452",
    name: "Hotel Matahari Prawirotaman",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8048,
    lng: 110.3688,
    address: "Jl. Prawirotaman No.15, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 70,
    capacity: 65,
    phone: "(0274) 372120",
    distance_tugu: "2.6 km dari Tugu",
    dist_malio: "2.4 km",
    dist_kraton: "1.9 km",
    photo: PHOTOS.b3[1],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 6.6,
    connectivity: 74,
    serviceLoad: 57,
    notes:
      "Salah satu hotel tertua di kawasan Prawirotaman. Arsitektur tradisional Jawa yang terawat.",
  },
  {
    id: "YK-HTL-453",
    name: "Hotel Bintang Fajar Umbulharjo",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8038,
    lng: 110.391,
    address: "Jl. Veteran No.147, Warungboto",
    kecamatan: "Umbulharjo",
    rooms: 68,
    capacity: 61,
    phone: "(0274) 519211",
    distance_tugu: "3.5 km dari Tugu",
    dist_malio: "3.3 km",
    dist_kraton: "2.8 km",
    photo: PHOTOS.b3[2],
    landuse: ["Komersial/Jasa", "Permukiman"],
    geodesign: 6.2,
    connectivity: 71,
    serviceLoad: 53,
    notes:
      "Hotel ekonomis di kawasan Umbulharjo. Akses mudah ke kampus UGM dan UNY.",
  },
  {
    id: "YK-HTL-454",
    name: "Hotel Dalem Puri Pakualaman",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7972,
    lng: 110.3765,
    address: "Jl. Sultan Agung No.8, Purwokinanti",
    kecamatan: "Pakualaman",
    rooms: 58,
    capacity: 59,
    phone: "(0274) 376543",
    distance_tugu: "1.6 km dari Tugu",
    dist_malio: "1.4 km",
    dist_kraton: "0.9 km",
    photo: PHOTOS.b3[3],
    landuse: ["Kawasan Heritage", "Kawasan Pariwisata"],
    geodesign: 7.0,
    connectivity: 82,
    serviceLoad: 52,
    notes:
      "Dekat Pura Pakualaman. Arsitektur hotel terinspirasi budaya Pakualaman, nilai heritage tinggi.",
  },
  {
    id: "YK-HTL-455",
    name: "Cakra Kusuma Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7898,
    lng: 110.371,
    address: "Jl. Kaliurang No.47, Baciro",
    kecamatan: "Gondokusuman",
    rooms: 95,
    capacity: 74,
    phone: "(0274) 589700",
    distance_tugu: "1.7 km dari Tugu",
    dist_malio: "1.5 km",
    dist_kraton: "1.8 km",
    photo: PHOTOS.b3[4],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 6.9,
    connectivity: 86,
    serviceLoad: 65,
    notes:
      "Hotel bintang 3 fasilitas lengkap. Dekat kampus UGM dan RS Panti Rapih.",
  },
  {
    id: "YK-HTL-456",
    name: "Hotel Sriwijaya Malioboro",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7958,
    lng: 110.3645,
    address: "Jl. Mataram No.13, Suryatmajan",
    kecamatan: "Danurejan",
    rooms: 87,
    capacity: 80,
    phone: "(0274) 562371",
    distance_tugu: "0.8 km dari Tugu",
    dist_malio: "0.3 km",
    dist_kraton: "0.9 km",
    photo: PHOTOS.b3[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 7.0,
    connectivity: 91,
    serviceLoad: 76,
    notes:
      "Lokasi strategis di kawasan Danurejan dekat Malioboro. Melayani wisatawan heritage.",
  },
  {
    id: "YK-HTL-462",
    name: "Hotel Kotagede Heritage",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8145,
    lng: 110.3878,
    address: "Jl. Tegalgendu No.8, Kotagede",
    kecamatan: "Kotagede",
    rooms: 52,
    capacity: 50,
    phone: "(0274) 385600",
    distance_tugu: "4.3 km dari Tugu",
    dist_malio: "4.1 km",
    dist_kraton: "3.2 km",
    photo: PHOTOS.b3[1],
    landuse: ["Kawasan Heritage", "Kawasan Bersejarah"],
    geodesign: 7.4,
    connectivity: 65,
    serviceLoad: 42,
    notes:
      "Hotel heritage Kotagede dalam bangunan cagar budaya. Pengalaman menginap autentik.",
  },
  {
    id: "YK-HTL-463",
    name: "Hotel Griya Persada Danurejan",
    category: "Bintang 3",
    stars: 3,
    lat: -7.796,
    lng: 110.3712,
    address: "Jl. Bhayangkara No.4, Suryatmajan",
    kecamatan: "Danurejan",
    rooms: 55,
    capacity: 68,
    phone: "(0274) 562800",
    distance_tugu: "1.0 km dari Tugu",
    dist_malio: "0.7 km",
    dist_kraton: "0.8 km",
    photo: PHOTOS.b3[2],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.9,
    connectivity: 87,
    serviceLoad: 64,
    notes:
      "Hotel budget di kawasan Danurejan. Dekat pusat belanja Malioboro dan Pasar Beringharjo.",
  },

  /* ═══ BUTIK ════════════════════════════════════════════ */
  {
    id: "YK-HTL-437",
    name: "Greenhost Boutique Hotel",
    category: "Butik",
    stars: 4,
    lat: -7.8077,
    lng: 110.3701,
    address: "Jl. Prawirotaman II No.629, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 57,
    capacity: 74,
    phone: "(0274) 387788",
    distance_tugu: "2.8 km dari Tugu",
    dist_malio: "2.6 km",
    dist_kraton: "2.1 km",
    photo: PHOTOS.butik[0],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 7.8,
    connectivity: 74,
    serviceLoad: 58,
    notes:
      "Eco-boutique hotel dengan konsep berkelanjutan. Panel surya dan sistem air daur ulang.",
  },
  {
    id: "YK-HTL-457",
    name: "Dalem Brontokusuman Heritage",
    category: "Butik",
    stars: 4,
    lat: -7.8058,
    lng: 110.366,
    address: "Jl. Brontokusuman No.23, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 22,
    capacity: 55,
    phone: "(0274) 372888",
    distance_tugu: "2.5 km dari Tugu",
    dist_malio: "2.3 km",
    dist_kraton: "1.7 km",
    photo: PHOTOS.butik[1],
    landuse: ["Kawasan Heritage", "Kawasan Pariwisata"],
    geodesign: 8.2,
    connectivity: 72,
    serviceLoad: 43,
    notes:
      "Heritage boutique hotel di bangunan Belanda 1920-an. Hanya 22 kamar, pengalaman autentik.",
  },
  {
    id: "YK-HTL-458",
    name: "Omah Heritage Kotagede",
    category: "Butik",
    stars: 3,
    lat: -7.8108,
    lng: 110.3882,
    address: "Jl. Mondorakan No.5, Purbayan",
    kecamatan: "Kotagede",
    rooms: 12,
    capacity: 48,
    phone: "(0274) 385456",
    distance_tugu: "4.2 km dari Tugu",
    dist_malio: "4.0 km",
    dist_kraton: "3.1 km",
    photo: PHOTOS.butik[0],
    landuse: ["Kawasan Heritage", "Kawasan Bersejarah"],
    geodesign: 8.0,
    connectivity: 65,
    serviceLoad: 40,
    notes:
      "Homestay heritage bekas rumah pengrajin perak. Wisata edukasi kerajinan tersedia.",
  },

  /* ═══ BINTANG 2 ════════════════════════════════════════ */
  {
    id: "YK-HTL-438",
    name: "Fave Hotel Malioboro",
    category: "Bintang 2",
    stars: 2,
    lat: -7.7935,
    lng: 110.366,
    address: "Jl. Dagen No.75, Ngampilan",
    kecamatan: "Gedongtengen",
    rooms: 64,
    capacity: 89,
    phone: "(0274) 565656",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.1 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b2[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.1,
    connectivity: 95,
    serviceLoad: 84,
    notes:
      "Hotel budget occupancy tinggi. Ketergantungan tinggi pada wisata massal kawasan Malioboro.",
  },
  {
    id: "YK-HTL-439",
    name: "POP! Hotel Sangaji Yogyakarta",
    category: "Bintang 2",
    stars: 2,
    lat: -7.7853,
    lng: 110.3698,
    address: "Jl. P. Sangaji No.59, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 76,
    capacity: 80,
    phone: "(0274) 564900",
    distance_tugu: "1.5 km dari Tugu",
    dist_malio: "1.3 km",
    dist_kraton: "1.6 km",
    photo: PHOTOS.b2[1],
    landuse: ["Permukiman", "Komersial/Jasa"],
    geodesign: 5.9,
    connectivity: 82,
    serviceLoad: 72,
    notes:
      "Budget hotel modern chain nasional. Desain compact efisien, melayani segmen milenial.",
  },
  {
    id: "YK-HTL-440",
    name: "Amaris Hotel Malioboro",
    category: "Bintang 2",
    stars: 2,
    lat: -7.7922,
    lng: 110.3652,
    address: "Jl. Pajeksan No.37, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 92,
    capacity: 77,
    phone: "(0274) 560800",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.1 km",
    photo: PHOTOS.b2[2],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.0,
    connectivity: 94,
    serviceLoad: 75,
    notes:
      "Budget chain hotel di lokasi premium. Konsep kamar minimalis efisien.",
  },
  {
    id: "YK-HTL-441",
    name: "Ibis Budget Malioboro Yogyakarta",
    category: "Bintang 2",
    stars: 2,
    lat: -7.794,
    lng: 110.3655,
    address: "Jl. Sosrowijayan No.35, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 108,
    capacity: 85,
    phone: "(0274) 566100",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b2[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 5.8,
    connectivity: 93,
    serviceLoad: 81,
    notes:
      "Budget brand internasional. Sasaran wisatawan backpacker Eropa dan Asia. Occupancy stabil.",
  },
  {
    id: "YK-HTL-442",
    name: "D'Green Hotel Prawirotaman",
    category: "Bintang 2",
    stars: 2,
    lat: -7.804,
    lng: 110.371,
    address: "Jl. Prawirotaman No.8, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 55,
    capacity: 64,
    phone: "(0274) 374001",
    distance_tugu: "2.5 km dari Tugu",
    dist_malio: "2.3 km",
    dist_kraton: "1.9 km",
    photo: PHOTOS.b2[1],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 5.7,
    connectivity: 72,
    serviceLoad: 52,
    notes:
      "Hotel kecil dengan taman tropis. Sasaran wisatawan independen yang mencari ketenangan.",
  },
  {
    id: "YK-HTL-459",
    name: "Wisma Bahtera Yogyakarta",
    category: "Bintang 2",
    stars: 2,
    lat: -7.8072,
    lng: 110.3558,
    address: "Jl. Parangtritis No.28, Mantrijeron",
    kecamatan: "Mantrijeron",
    rooms: 48,
    capacity: 57,
    phone: "(0274) 377100",
    distance_tugu: "2.9 km dari Tugu",
    dist_malio: "2.7 km",
    dist_kraton: "2.3 km",
    photo: PHOTOS.b2[2],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 5.5,
    connectivity: 70,
    serviceLoad: 50,
    notes:
      "Penginapan budget di koridor wisata Parangtritis. Fasilitas sederhana namun bersih.",
  },

  {
    id: "YK-HTL-461",
    name: "POP! Hotel Malioboro Yogyakarta",
    category: "Bintang 2",
    stars: 2,
    lat: -7.7965,
    lng: 110.367,
    address: "Jl. Mangkubumi No.4, Gowongan",
    kecamatan: "Jetis",
    rooms: 110,
    capacity: 88,
    phone: "(0274) 568900",
    distance_tugu: "0.6 km dari Tugu",
    dist_malio: "0.4 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b2[1],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.0,
    connectivity: 92,
    serviceLoad: 82,
    notes:
      "Budget chain hotel sangat dekat Malioboro. Occupancy tinggi sepanjang tahun.",
  },
];

/* ── Hitung WSM untuk setiap hotel ─────────────────────── */
const HOTELS = HOTELS_RAW.map((h) => ({ ...h, wsm: calcWSM(h) }));

/* ── Statistik ───────────────────────────────────────────── */
const KECAMATAN_STATS = (() => {
  const m = {};
  HOTELS.forEach((h) => {
    m[h.kecamatan] = (m[h.kecamatan] || 0) + 1;
  });
  return Object.entries(m)
    .sort((a, b) => b[1] - a[1])
    .map(([name, count]) => ({ name, count }));
})();

const CAT_STATS = (() => {
  const m = {};
  HOTELS.forEach((h) => {
    m[h.category] = (m[h.category] || 0) + 1;
  });
  return m;
})();

/* ── Ranking WSM (tertinggi ke terendah) ─────────────────── */
const WSM_RANKING = [...HOTELS].sort((a, b) => b.wsm - a.wsm);
