/* ============================================================
   DATA.JS — Hotel Dataset, 42 Entitas, Yogyakarta
   WebGIS SIG Terapan — Geomatika
   ============================================================ */

const YOGYA_CENTER = [-7.7956, 110.3695];
const YOGYA_ZOOM = 13;

const CAT_META = {
  "Bintang 5": { color: "#D97706", bg: "rgba(217,119,6,.12)", label: "★★★★★" },
  "Bintang 4": { color: "#2563EB", bg: "rgba(37,99,235,.10)", label: "★★★★" },
  "Bintang 3": { color: "#7C3AED", bg: "rgba(124,58,237,.10)", label: "★★★" },
  "Bintang 2": { color: "#64748B", bg: "rgba(100,116,139,.12)", label: "★★" },
  Butik: { color: "#0B9F97", bg: "rgba(11,159,151,.10)", label: "BOUTIQUE" },
};

/* Unsplash photo IDs mapped to hotel categories */
const PHOTOS = {
  b5: [
    "https://images.unsplash.com/photo-1551882547-ff40c4a49f8e?w=420&q=80",
    "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=420&q=80",
    "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=420&q=80",
    "https://images.unsplash.com/photo-1455587734955-081b22074882?w=420&q=80",
    "https://images.unsplash.com/photo-1580041065738-e72023775cdc?w=420&q=80",
  ],
  b4: [
    "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=420&q=80",
    "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=420&q=80",
    "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=420&q=80",
    "https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=420&q=80",
    "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=420&q=80",
  ],
  b3: [
    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=420&q=80",
    "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=420&q=80",
    "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=420&q=80",
    "https://images.unsplash.com/photo-1551776235-dde6d482980b?w=420&q=80",
  ],
  b2: [
    "https://images.unsplash.com/photo-1586611292717-f828b167408c?w=420&q=80",
    "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=420&q=80",
  ],
};

const HOTELS = [
  /* ── BINTANG 5 ── */
  {
    id: "YK-HTL-401",
    name: "Grand Inna Malioboro",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7928,
    lng: 110.365,
    address: "Jl. Malioboro No.60, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 241,
    capacity: 88,
    phone: "(0274) 563041",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.1 km",
    dist_kraton: "1.2 km",
    photo: PHOTOS.b5[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 8.1,
    connectivity: 94,
    serviceLoad: 71,
    notes:
      "Berada di jantung koridor heritage Malioboro. Bangunan bersejarah dilindungi SK Gubernur DIY.",
  },
  {
    id: "YK-HTL-402",
    name: "The Phoenix Hotel Yogyakarta",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7902,
    lng: 110.3642,
    address: "Jl. Jend. Sudirman No.9, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 143,
    capacity: 92,
    phone: "(0274) 566617",
    distance_tugu: "0.4 km dari Tugu",
    dist_malio: "0.3 km",
    dist_kraton: "1.4 km",
    photo: PHOTOS.b5[1],
    landuse: ["Zonasi Cagar Budaya", "Komersial/Jasa"],
    geodesign: 8.4,
    connectivity: 92,
    serviceLoad: 64,
    notes:
      "Subject located within the heritage corridor (Kawasan Cagar Budaya Jetis). Height regulation max 18m verified per 2023 spatial audit.",
  },
  {
    id: "YK-HTL-403",
    name: "Tentrem Hotel Yogyakarta",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7885,
    lng: 110.3665,
    address: "Jl. P. Diponegoro No.72, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 197,
    capacity: 85,
    phone: "(0274) 563888",
    distance_tugu: "0.6 km dari Tugu",
    dist_malio: "0.5 km",
    dist_kraton: "1.5 km",
    photo: PHOTOS.b5[2],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 8.7,
    connectivity: 96,
    serviceLoad: 58,
    notes:
      "Hotel bintang 5 dengan konsep budaya Jawa kontemporer. Aksesibilitas pejalan kaki sangat baik.",
  },
  {
    id: "YK-HTL-404",
    name: "Melia Purosani Hotel",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7892,
    lng: 110.371,
    address: "Jl. Suryotomo No.31, Ngupasan",
    kecamatan: "Gondomanan",
    rooms: 326,
    capacity: 79,
    phone: "(0274) 589521",
    distance_tugu: "0.8 km dari Tugu",
    dist_malio: "0.6 km",
    dist_kraton: "0.9 km",
    photo: PHOTOS.b5[3],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 8.2,
    connectivity: 89,
    serviceLoad: 73,
    notes:
      "Hotel MICE terbesar di pusat kota. Kapasitas konvensi mendukung kegiatan skala internasional.",
  },
  {
    id: "YK-HTL-405",
    name: "Hyatt Regency Yogyakarta",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7778,
    lng: 110.3803,
    address: "Jl. Palagan Tentara Pelajar, Sariharjo",
    kecamatan: "Ngaglik",
    rooms: 269,
    capacity: 76,
    phone: "(0274) 869123",
    distance_tugu: "4.2 km dari Tugu",
    dist_malio: "4.5 km",
    dist_kraton: "5.1 km",
    photo: PHOTOS.b5[4],
    landuse: ["Kawasan Pariwisata", "Ruang Terbuka Hijau"],
    geodesign: 9.1,
    connectivity: 78,
    serviceLoad: 45,
    notes:
      "Kawasan utara dengan RTH signifikan. Vegetasi index tertinggi di antara hotel bintang 5.",
  },
  {
    id: "YK-HTL-406",
    name: "Royal Ambarrukmo Yogyakarta",
    category: "Bintang 5",
    stars: 5,
    lat: -7.783,
    lng: 110.395,
    address: "Jl. Laksda Adisucipto No.81, Caturtunggal",
    kecamatan: "Depok",
    rooms: 237,
    capacity: 82,
    phone: "(0274) 488488",
    distance_tugu: "5.1 km dari Tugu",
    dist_malio: "5.3 km",
    dist_kraton: "4.9 km",
    photo: PHOTOS.b5[0],
    landuse: ["Kawasan Pariwisata", "Kawasan Bersejarah"],
    geodesign: 8.5,
    connectivity: 87,
    serviceLoad: 61,
    notes:
      "Komplek hotel warisan Keraton Ambarrukmo. Nilai heritage tinggi, dilindungi SK Bupati Sleman.",
  },
  {
    id: "YK-HTL-407",
    name: "Grand Mercure Yogyakarta Adi Sucipto",
    category: "Bintang 5",
    stars: 5,
    lat: -7.782,
    lng: 110.394,
    address: "Jl. Laksda Adisucipto No.38, Caturtunggal",
    kecamatan: "Depok",
    rooms: 185,
    capacity: 88,
    phone: "(0274) 484888",
    distance_tugu: "4.9 km dari Tugu",
    dist_malio: "5.1 km",
    dist_kraton: "4.7 km",
    photo: PHOTOS.b5[1],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 8.0,
    connectivity: 85,
    serviceLoad: 68,
    notes:
      "Dekat Bandara Adisutjipto. Tingkat hunian tinggi pada hari kerja, dominan tamu bisnis.",
  },
  {
    id: "YK-HTL-408",
    name: "Sheraton Mustika Yogyakarta Resort & Spa",
    category: "Bintang 5",
    stars: 5,
    lat: -7.8058,
    lng: 110.4031,
    address: "Jl. Laksda Adisucipto Km 8.7",
    kecamatan: "Umbulharjo",
    rooms: 234,
    capacity: 73,
    phone: "(0274) 488588",
    distance_tugu: "5.5 km dari Tugu",
    dist_malio: "5.8 km",
    dist_kraton: "5.2 km",
    photo: PHOTOS.b5[2],
    landuse: ["Kawasan Pariwisata", "Ruang Terbuka Hijau"],
    geodesign: 8.6,
    connectivity: 80,
    serviceLoad: 52,
    notes:
      "Resort mewah dengan SPA kelas dunia. Fasilitas kolam renang olimpik mendukung wisatawan premium.",
  },
  {
    id: "YK-HTL-409",
    name: "Tugu Yogyakarta Hotel",
    category: "Bintang 5",
    stars: 5,
    lat: -7.7847,
    lng: 110.3636,
    address: "Jl. P. Mangkubumi No.18, Gowongan",
    kecamatan: "Jetis",
    rooms: 48,
    capacity: 70,
    phone: "(0274) 563611",
    distance_tugu: "0.1 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.7 km",
    photo: PHOTOS.b5[3],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 8.9,
    connectivity: 97,
    serviceLoad: 48,
    notes:
      "Butik hotel bintang 5 ikonik di samping Tugu Yogyakarta. Koleksi artefak seni Jawa klasik yang unik.",
  },

  /* ── BINTANG 4 ── */
  {
    id: "YK-HTL-410",
    name: "Harper Malioboro by ASTON",
    category: "Bintang 4",
    stars: 4,
    lat: -7.796,
    lng: 110.3638,
    address: "Jl. Dagen No.47, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 166,
    capacity: 91,
    phone: "(0274) 566066",
    distance_tugu: "0.2 km dari Tugu",
    dist_malio: "0.1 km",
    dist_kraton: "1.3 km",
    photo: PHOTOS.b4[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 7.8,
    connectivity: 97,
    serviceLoad: 82,
    notes:
      "Occupancy tertinggi di kawasan Malioboro. Beban layanan melebihi optimal pada peak season.",
  },
  {
    id: "YK-HTL-411",
    name: "Hotel Santika Premiere Jogja",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7882,
    lng: 110.3734,
    address: "Jl. Jend. Sudirman No.19, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 212,
    capacity: 74,
    phone: "(0274) 563036",
    distance_tugu: "1.1 km dari Tugu",
    dist_malio: "0.9 km",
    dist_kraton: "1.1 km",
    photo: PHOTOS.b4[1],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.9,
    connectivity: 91,
    serviceLoad: 57,
    notes:
      "Lokasi strategis di segitiga emas pariwisata Yogyakarta. Akses mudah ke Malioboro dan Kraton.",
  },
  {
    id: "YK-HTL-412",
    name: "Novotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7868,
    lng: 110.3743,
    address: "Jl. Jend. Sudirman No.89, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 195,
    capacity: 69,
    phone: "(0274) 580930",
    distance_tugu: "1.3 km dari Tugu",
    dist_malio: "1.1 km",
    dist_kraton: "0.9 km",
    photo: PHOTOS.b4[2],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.6,
    connectivity: 88,
    serviceLoad: 52,
    notes:
      "Desain bangunan mempertimbangkan koridor pandang visual ke Merapi. Sesuai RTBL Koridor Sudirman.",
  },
  {
    id: "YK-HTL-413",
    name: "Indoluxe Hotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7843,
    lng: 110.3688,
    address: "Jl. Kapten Piere Tendean, Wirobrajan",
    kecamatan: "Wirobrajan",
    rooms: 178,
    capacity: 77,
    phone: "(0274) 566222",
    distance_tugu: "1.8 km dari Tugu",
    dist_malio: "1.6 km",
    dist_kraton: "1.9 km",
    photo: PHOTOS.b4[3],
    landuse: ["Komersial/Jasa", "Permukiman"],
    geodesign: 7.4,
    connectivity: 82,
    serviceLoad: 59,
    notes:
      "Kawasan transisi komersial-permukiman. Dampak terhadap jaringan jalan perlu monitoring berkelanjutan.",
  },
  {
    id: "YK-HTL-414",
    name: "Cavinton Hotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.795,
    lng: 110.382,
    address: "Jl. Ipda Tut Harsono No.47, Semaki",
    kecamatan: "Umbulharjo",
    rooms: 134,
    capacity: 83,
    phone: "(0274) 547777",
    distance_tugu: "2.9 km dari Tugu",
    dist_malio: "2.7 km",
    dist_kraton: "2.3 km",
    photo: PHOTOS.b4[4],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.1,
    connectivity: 79,
    serviceLoad: 66,
    notes:
      "Kawasan timur kota dengan aksesibilitas berkembang pesat. Infrastruktur jalan dalam kondisi baik.",
  },
  {
    id: "YK-HTL-415",
    name: "Swiss-Belinn Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.8105,
    lng: 110.3635,
    address: "Jl. Parangtritis Km 1, Mantrijeron",
    kecamatan: "Mantrijeron",
    rooms: 156,
    capacity: 72,
    phone: "(0274) 411234",
    distance_tugu: "3.4 km dari Tugu",
    dist_malio: "3.1 km",
    dist_kraton: "2.6 km",
    photo: PHOTOS.b4[0],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.3,
    connectivity: 76,
    serviceLoad: 54,
    notes:
      "Koridor selatan menuju Parangtritis. Potensi wisata alam tinggi, aksesibilitas sedang berkembang.",
  },
  {
    id: "YK-HTL-416",
    name: "Harris Hotel & Conventions Malioboro",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7942,
    lng: 110.3644,
    address: "Jl. Pabringan No.2, Ngupasan",
    kecamatan: "Gondomanan",
    rooms: 222,
    capacity: 80,
    phone: "(0274) 588222",
    distance_tugu: "0.5 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "0.7 km",
    photo: PHOTOS.b4[1],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 7.7,
    connectivity: 95,
    serviceLoad: 78,
    notes:
      "Hotel convention scale besar di pusat kota. Ballroom kapasitas 2000 pax mendukung MICE.",
  },
  {
    id: "YK-HTL-417",
    name: "Rich Jogja Hotel",
    category: "Bintang 4",
    stars: 4,
    lat: -7.771,
    lng: 110.362,
    address: "Jl. Magelang Km 4, Sinduadi",
    kecamatan: "Mlati",
    rooms: 148,
    capacity: 65,
    phone: "(0274) 865500",
    distance_tugu: "2.8 km dari Tugu",
    dist_malio: "3.1 km",
    dist_kraton: "4.2 km",
    photo: PHOTOS.b4[2],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 6.9,
    connectivity: 72,
    serviceLoad: 48,
    notes:
      "Koridor barat laut menuju Magelang. Segmen tamu wisatawan keluarga mendominasi.",
  },
  {
    id: "YK-HTL-418",
    name: "Grand Quality Hotel Yogyakarta",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7815,
    lng: 110.3893,
    address: "Jl. Laksda Adisucipto No.48, Demangan",
    kecamatan: "Gondokusuman",
    rooms: 176,
    capacity: 68,
    phone: "(0274) 485858",
    distance_tugu: "2.4 km dari Tugu",
    dist_malio: "2.6 km",
    dist_kraton: "2.8 km",
    photo: PHOTOS.b4[3],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.2,
    connectivity: 83,
    serviceLoad: 55,
    notes:
      "Hotel bisnis di koridor timur dekat bandara. Aksesibilitas kendaraan bermotor sangat baik.",
  },
  {
    id: "YK-HTL-419",
    name: "Alana Hotel & Convention Center",
    category: "Bintang 4",
    stars: 4,
    lat: -7.769,
    lng: 110.3803,
    address: "Jl. Palagan Tentara Pelajar Km 7",
    kecamatan: "Ngaglik",
    rooms: 203,
    capacity: 71,
    phone: "(0274) 867123",
    distance_tugu: "4.5 km dari Tugu",
    dist_malio: "4.8 km",
    dist_kraton: "5.5 km",
    photo: PHOTOS.b4[4],
    landuse: ["Kawasan Pariwisata", "Ruang Terbuka Hijau"],
    geodesign: 7.5,
    connectivity: 74,
    serviceLoad: 49,
    notes:
      "Kawasan utara dengan green space memadai. Convention center mendukung kegiatan skala regional.",
  },
  {
    id: "YK-HTL-420",
    name: "The Jayakarta Yogyakarta Hotel",
    category: "Bintang 4",
    stars: 4,
    lat: -7.7862,
    lng: 110.3914,
    address: "Jl. Laksda Adisucipto No.28, Demangan",
    kecamatan: "Gondokusuman",
    rooms: 189,
    capacity: 67,
    phone: "(0274) 564222",
    distance_tugu: "2.6 km dari Tugu",
    dist_malio: "2.8 km",
    dist_kraton: "3.0 km",
    photo: PHOTOS.b4[0],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.0,
    connectivity: 81,
    serviceLoad: 53,
    notes:
      "Kolam renang outdoor dengan view taman. Fasilitas spa dan fitness center lengkap.",
  },
  {
    id: "YK-HTL-421",
    name: "Premiere Park Hotel Wonosari",
    category: "Bintang 4",
    stars: 4,
    lat: -7.824,
    lng: 110.4078,
    address: "Jl. Wonosari Km 9, Banguntapan",
    kecamatan: "Banguntapan",
    rooms: 134,
    capacity: 61,
    phone: "(0274) 442244",
    distance_tugu: "7.1 km dari Tugu",
    dist_malio: "7.4 km",
    dist_kraton: "6.8 km",
    photo: PHOTOS.b4[1],
    landuse: ["Kawasan Pariwisata", "Kawasan Campuran"],
    geodesign: 6.8,
    connectivity: 67,
    serviceLoad: 42,
    notes:
      "Hotel transit di jalan Wonosari. Melayani wisatawan menuju Gunungkidul dan pantai selatan.",
  },

  /* ── BINTANG 3 ── */
  {
    id: "YK-HTL-422",
    name: "Artotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8001,
    lng: 110.3686,
    address: "Jl. Kaliurang No.14, Baciro",
    kecamatan: "Gondokusuman",
    rooms: 109,
    capacity: 86,
    phone: "(0274) 547200",
    distance_tugu: "1.9 km dari Tugu",
    dist_malio: "1.7 km",
    dist_kraton: "2.1 km",
    photo: PHOTOS.b3[0],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.0,
    connectivity: 84,
    serviceLoad: 71,
    notes:
      "Hotel seni kontemporer. Koleksi artwork lokal menjadi nilai jual unik bagi wisatawan budaya.",
  },
  {
    id: "YK-HTL-423",
    name: "Ibis Styles Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7927,
    lng: 110.3707,
    address: "Jl. Dagen No.67, Ngampilan",
    kecamatan: "Gedongtengen",
    rooms: 130,
    capacity: 93,
    phone: "(0274) 580555",
    distance_tugu: "0.5 km dari Tugu",
    dist_malio: "0.3 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b3[1],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 7.5,
    connectivity: 95,
    serviceLoad: 88,
    notes:
      "Occupancy sangat tinggi (93%). Terindikasi beban layanan berlebih pada musim peak.",
  },
  {
    id: "YK-HTL-424",
    name: "Neo Malioboro Hotel",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7919,
    lng: 110.3648,
    address: "Jl. Pajeksan No.18, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 98,
    capacity: 78,
    phone: "(0274) 589300",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.1 km",
    photo: PHOTOS.b3[2],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.8,
    connectivity: 96,
    serviceLoad: 75,
    notes:
      "Lokasi premium kawasan heritage. Indeks kerapatan bangunan tinggi, limitasi ekspansi vertikal.",
  },
  {
    id: "YK-HTL-425",
    name: "Hotel Mutiara Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7943,
    lng: 110.3669,
    address: "Jl. Malioboro No.18, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 93,
    capacity: 65,
    phone: "(0274) 563814",
    distance_tugu: "0.4 km dari Tugu",
    dist_malio: "0.1 km",
    dist_kraton: "1.2 km",
    photo: PHOTOS.b3[3],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.5,
    connectivity: 93,
    serviceLoad: 62,
    notes:
      "Hotel heritage generasi pertama di Malioboro. Nilai arsitektural dilindungi sebagai cagar budaya.",
  },
  {
    id: "YK-HTL-426",
    name: "Hotel Pesona Jogja",
    category: "Bintang 3",
    stars: 3,
    lat: -7.805,
    lng: 110.372,
    address: "Jl. Prawirotaman No.1, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 87,
    capacity: 70,
    phone: "(0274) 373900",
    distance_tugu: "2.5 km dari Tugu",
    dist_malio: "2.3 km",
    dist_kraton: "1.8 km",
    photo: PHOTOS.b3[0],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 6.9,
    connectivity: 77,
    serviceLoad: 58,
    notes:
      "Kawasan Prawirotaman sebagai pusat hotel butik. Karakteristik kampung wisata kepadatan rendah.",
  },
  {
    id: "YK-HTL-427",
    name: "Puri Artha Hotel",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7998,
    lng: 110.3878,
    address: "Jl. Cendrawasih No.36, Semaki",
    kecamatan: "Umbulharjo",
    rooms: 76,
    capacity: 60,
    phone: "(0274) 563288",
    distance_tugu: "3.1 km dari Tugu",
    dist_malio: "2.9 km",
    dist_kraton: "2.5 km",
    photo: PHOTOS.b3[1],
    landuse: ["Permukiman", "Komersial/Jasa"],
    geodesign: 6.3,
    connectivity: 74,
    serviceLoad: 48,
    notes:
      "Hotel di kawasan permukiman dengan konversi lahan bertahap. Dampak terhadap RTH perlu evaluasi.",
  },
  {
    id: "YK-HTL-428",
    name: "Saphir Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7915,
    lng: 110.3762,
    address: "Jl. Laksda Adisucipto No.38, Demangan",
    kecamatan: "Gondokusuman",
    rooms: 118,
    capacity: 73,
    phone: "(0274) 485555",
    distance_tugu: "2.2 km dari Tugu",
    dist_malio: "2.0 km",
    dist_kraton: "2.4 km",
    photo: PHOTOS.b3[2],
    landuse: ["Komersial/Jasa", "Kawasan Campuran"],
    geodesign: 7.2,
    connectivity: 86,
    serviceLoad: 61,
    notes:
      "Koridor timur menuju bandara. Segmen tamu didominasi wisatawan transit.",
  },
  {
    id: "YK-HTL-429",
    name: "Whiz Prime Hotel Malioboro",
    category: "Bintang 3",
    stars: 3,
    lat: -7.79,
    lng: 110.3663,
    address: "Jl. Mangkubumi No.52, Gowongan",
    kecamatan: "Jetis",
    rooms: 122,
    capacity: 81,
    phone: "(0274) 566300",
    distance_tugu: "0.7 km dari Tugu",
    dist_malio: "0.5 km",
    dist_kraton: "1.3 km",
    photo: PHOTOS.b3[3],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 7.0,
    connectivity: 90,
    serviceLoad: 74,
    notes:
      "Dekat kawasan Malioboro dan Stasiun Tugu. Aksesibilitas transit sangat baik.",
  },
  {
    id: "YK-HTL-430",
    name: "Dafam Fortuna Malioboro",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7878,
    lng: 110.365,
    address: "Jl. Mangkubumi No.47, Gowongan",
    kecamatan: "Jetis",
    rooms: 105,
    capacity: 77,
    phone: "(0274) 587200",
    distance_tugu: "0.9 km dari Tugu",
    dist_malio: "0.7 km",
    dist_kraton: "1.5 km",
    photo: PHOTOS.b3[0],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 6.9,
    connectivity: 88,
    serviceLoad: 70,
    notes:
      "Hotel budget premium di koridor Mangkubumi. Target pasar backpacker kelas menengah.",
  },
  {
    id: "YK-HTL-431",
    name: "Horison Express Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7948,
    lng: 110.3672,
    address: "Jl. Dagen No.85, Ngampilan",
    kecamatan: "Gedongtengen",
    rooms: 114,
    capacity: 84,
    phone: "(0274) 563999",
    distance_tugu: "0.4 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.1 km",
    photo: PHOTOS.b3[1],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.7,
    connectivity: 94,
    serviceLoad: 79,
    notes:
      "Hotel express dengan lokasi prime. Fasilitas efisien untuk wisatawan singkat.",
  },
  {
    id: "YK-HTL-432",
    name: "Adhisthana Hotel Prawirotaman",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8065,
    lng: 110.3695,
    address: "Jl. Prawirotaman II No.16, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 81,
    capacity: 68,
    phone: "(0274) 377222",
    distance_tugu: "2.7 km dari Tugu",
    dist_malio: "2.5 km",
    dist_kraton: "2.0 km",
    photo: PHOTOS.b3[2],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 6.8,
    connectivity: 75,
    serviceLoad: 56,
    notes:
      "Butik hotel tenang di kawasan Prawirotaman. Kolam renang privat dan restoran rooftop.",
  },
  {
    id: "YK-HTL-433",
    name: "Tjokro Style Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.7858,
    lng: 110.3756,
    address: "Jl. Jend. Sudirman No.75, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 96,
    capacity: 72,
    phone: "(0274) 512345",
    distance_tugu: "1.4 km dari Tugu",
    dist_malio: "1.2 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b3[3],
    landuse: ["Kawasan Pariwisata", "Komersial/Jasa"],
    geodesign: 6.9,
    connectivity: 85,
    serviceLoad: 63,
    notes:
      "Hotel boutique dengan sentuhan desain Jawa modern. Meeting room kapasitas 200 pax.",
  },
  {
    id: "YK-HTL-434",
    name: "Brongto Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.798,
    lng: 110.3844,
    address: "Jl. Aipda Tut Harsono No.15, Muja Muju",
    kecamatan: "Umbulharjo",
    rooms: 88,
    capacity: 66,
    phone: "(0274) 542200",
    distance_tugu: "2.8 km dari Tugu",
    dist_malio: "2.6 km",
    dist_kraton: "2.2 km",
    photo: PHOTOS.b3[0],
    landuse: ["Komersial/Jasa", "Permukiman"],
    geodesign: 6.4,
    connectivity: 73,
    serviceLoad: 51,
    notes:
      "Hotel keluarga di kawasan tenang Umbulharjo. Parkir luas dan restoran kapasitas 150 kursi.",
  },
  {
    id: "YK-HTL-435",
    name: "Puri Pangeran Hotel Yogyakarta",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8003,
    lng: 110.3622,
    address: "Jl. Rotowijayan No.5, Kraton",
    kecamatan: "Kraton",
    rooms: 72,
    capacity: 62,
    phone: "(0274) 372055",
    distance_tugu: "2.1 km dari Tugu",
    dist_malio: "1.5 km",
    dist_kraton: "0.3 km",
    photo: PHOTOS.b3[1],
    landuse: ["Kawasan Heritage", "Kawasan Kraton"],
    geodesign: 7.3,
    connectivity: 80,
    serviceLoad: 55,
    notes:
      "Dalam kawasan buffer Kraton Yogyakarta. Regulasi ketat pembangunan vertikal, max 8m.",
  },
  {
    id: "YK-HTL-436",
    name: "Grage Jogja Hotel",
    category: "Bintang 3",
    stars: 3,
    lat: -7.8018,
    lng: 110.3578,
    address: "Jl. Tentara Rakyat Mataram No.10, Pakuncen",
    kecamatan: "Wirobrajan",
    rooms: 94,
    capacity: 69,
    phone: "(0274) 562646",
    distance_tugu: "2.4 km dari Tugu",
    dist_malio: "1.9 km",
    dist_kraton: "1.6 km",
    photo: PHOTOS.b3[2],
    landuse: ["Komersial/Jasa", "Permukiman"],
    geodesign: 6.5,
    connectivity: 76,
    serviceLoad: 57,
    notes:
      "Hotel konvensional dengan kolam renang. Dekat pusat perbelanjaan dan rumah makan lokal.",
  },
  {
    id: "YK-HTL-437",
    name: "Greenhost Boutique Hotel",
    category: "Butik",
    stars: 4,
    lat: -7.8077,
    lng: 110.3701,
    address: "Jl. Prawirotaman II No.629, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 57,
    capacity: 74,
    phone: "(0274) 387788",
    distance_tugu: "2.8 km dari Tugu",
    dist_malio: "2.6 km",
    dist_kraton: "2.1 km",
    photo: PHOTOS.b4[3],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 7.8,
    connectivity: 74,
    serviceLoad: 58,
    notes:
      "Eco-boutique hotel dengan konsep berkelanjutan. Panel surya dan sistem air daur ulang.",
  },

  /* ── BINTANG 2 ── */
  {
    id: "YK-HTL-438",
    name: "Fave Hotel Malioboro",
    category: "Bintang 2",
    stars: 2,
    lat: -7.7935,
    lng: 110.366,
    address: "Jl. Dagen No.75, Ngampilan",
    kecamatan: "Gedongtengen",
    rooms: 64,
    capacity: 89,
    phone: "(0274) 565656",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.1 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b2[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.1,
    connectivity: 95,
    serviceLoad: 84,
    notes:
      "Hotel budget dengan occupancy tinggi. Ketergantungan tinggi pada wisata massal kawasan Malioboro.",
  },
  {
    id: "YK-HTL-439",
    name: "POP! Hotel Sangaji Yogyakarta",
    category: "Bintang 2",
    stars: 2,
    lat: -7.7853,
    lng: 110.3698,
    address: "Jl. P. Sangaji No.59, Cokrodiningratan",
    kecamatan: "Jetis",
    rooms: 76,
    capacity: 80,
    phone: "(0274) 564900",
    distance_tugu: "1.5 km dari Tugu",
    dist_malio: "1.3 km",
    dist_kraton: "1.6 km",
    photo: PHOTOS.b2[1],
    landuse: ["Permukiman", "Komersial/Jasa"],
    geodesign: 5.9,
    connectivity: 82,
    serviceLoad: 72,
    notes:
      "Budget hotel modern chain nasional. Desain compact efisien, melayani segmen milenial.",
  },
  {
    id: "YK-HTL-440",
    name: "Amaris Hotel Malioboro",
    category: "Bintang 2",
    stars: 2,
    lat: -7.7922,
    lng: 110.3652,
    address: "Jl. Pajeksan No.37, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 92,
    capacity: 77,
    phone: "(0274) 560800",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.1 km",
    photo: PHOTOS.b2[0],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 6.0,
    connectivity: 94,
    serviceLoad: 75,
    notes:
      "Budget chain hotel di lokasi premium. Konsep kamar minimalis efisien.",
  },
  {
    id: "YK-HTL-441",
    name: "Ibis Budget Malioboro Yogyakarta",
    category: "Bintang 2",
    stars: 2,
    lat: -7.794,
    lng: 110.3655,
    address: "Jl. Sosrowijayan No.35, Sosromenduran",
    kecamatan: "Gedongtengen",
    rooms: 108,
    capacity: 85,
    phone: "(0274) 566100",
    distance_tugu: "0.3 km dari Tugu",
    dist_malio: "0.2 km",
    dist_kraton: "1.0 km",
    photo: PHOTOS.b2[1],
    landuse: ["Kawasan Heritage", "Komersial/Jasa"],
    geodesign: 5.8,
    connectivity: 93,
    serviceLoad: 81,
    notes:
      "Budget brand internasional. Sasaran wisatawan backpacker Eropa dan Asia. Occupancy stabil.",
  },
  {
    id: "YK-HTL-442",
    name: "D'Green Hotel Prawirotaman",
    category: "Bintang 2",
    stars: 2,
    lat: -7.804,
    lng: 110.371,
    address: "Jl. Prawirotaman No.8, Brontokusuman",
    kecamatan: "Mergangsan",
    rooms: 55,
    capacity: 64,
    phone: "(0274) 374001",
    distance_tugu: "2.5 km dari Tugu",
    dist_malio: "2.3 km",
    dist_kraton: "1.9 km",
    photo: PHOTOS.b2[0],
    landuse: ["Kawasan Pariwisata", "Permukiman"],
    geodesign: 5.7,
    connectivity: 72,
    serviceLoad: 52,
    notes:
      "Hotel kecil dengan taman tropis. Sasaran wisatawan independen yang mencari ketenangan.",
  },
];

/* Kecamatan summary auto-built */
const KECAMATAN_STATS = (() => {
  const m = {};
  HOTELS.forEach((h) => {
    m[h.kecamatan] = (m[h.kecamatan] || 0) + 1;
  });
  return Object.entries(m)
    .sort((a, b) => b[1] - a[1])
    .map(([name, count]) => ({ name, count }));
})();

/* Category summary */
const CAT_STATS = (() => {
  const m = {};
  HOTELS.forEach((h) => {
    m[h.category] = (m[h.category] || 0) + 1;
  });
  return m;
})();
